import { type NextPage } from "next";
import Head from "next/head";
import { useEffect, useRef, useState } from "react";

const Home: NextPage = () => {
  const [data, setData] = useState([]);
  const [isLoading, setLoading] = useState(false);
  const [query, setQuery] = useState("");
  function onSubmit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault();
  }
  // const handleSearch = (e: any) => {
  //   setQuery(e.currentTarget.value);
  // };
  useEffect(() => {
    setLoading(true);
    const delayDebounceFn = setTimeout(() => {
      fetch(
        `https://free-nba.p.rapidapi.com/players?page=0&per_page=5&search=${query.trim()}`,
        {
          headers: {
            "x-rapidapi-key":
              "48b2d94655mshc2b2fc24eb62e29p13cc67jsnca0ac483e7ef",
            "x-rapidapi-host": "free-nba.p.rapidapi.com",
          },
        }
      )
        .then((res) => res.json())
        .then((data) => {
          setData(data.data);
          setLoading(false);
        });
    }, 800);
    return () => clearTimeout(delayDebounceFn);
  }, [query]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-start bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white">
        <div className="mt-40 flex w-80 flex-col gap-4 lg:mt-80 ">
          <input
            value={query}
            onChange={(e) => setQuery(e.currentTarget.value)}
            type="text"
            placeholder="Player Name"
            className="rounded-md bg-white/10 px-2 py-2 text-center text-xl tracking-wider ring-1 ring-white/20 placeholder:text-violet-200/40 focus:outline-violet-200"
          />
          <div className="flex flex-col gap-2">
            {isLoading ? (
              <p className="py-2 text-center text-white/50">Loading...</p>
            ) : query === "" ? (
              <p></p>
            ) : (
              data.map((e: any) => (
                <div className="flex flex-col items-center justify-center rounded-md bg-white/5 py-2 px-2">
                  <div className="flex w-full flex-col items-center gap-2">
                    <div className="font-bold">
                      {e.first_name + " " + e.last_name}
                    </div>
                    <div className="h-[1px] w-3/5 bg-white/20 "></div>
                    <div className=" text-xs text-white">
                      {e.team.full_name}
                    </div>
                    <div className="text-xs text-white/80">
                      position: {e.position}
                      {e.height_feet ? " | " + e.height_feet + " feet" : ""}
                      {e.weight_pounds
                        ? " | " + e.weight_pounds + " pounds"
                        : ""}
                    </div>
                  </div>
                </div>
              ))
            )}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
